"""
Mock bank data — симуляция серверной базы данных ВТБ.

Структура основана на Open Banking UK v3.1 + ISO 20022 + ЦБ РФ ФАПИ.
Данные полностью вымышленные, для демонстрации прототипа.

Пользователи (персоны из исследования N=97):
  vitya  — Студент, 22 года,              PIN 1111
  olga   — Финансовый менеджер, 38 лет,   PIN 2222
  artyom — Маркетолог, 29 лет,            PIN 3333
"""

# ---------------------------------------------------------------------------
# MCC коды (Merchant Category Codes) — ISO 18245
# ---------------------------------------------------------------------------
MCC = {
    "5411": "Супермаркеты",
    "5812": "Кафе и рестораны",
    "5814": "Фастфуд",
    "5541": "АЗС",
    "5651": "Одежда и обувь",
    "5912": "Аптеки",
    "5815": "Цифровые сервисы / подписки",
    "4111": "Транспорт",
    "7941": "Спорт и фитнес",
    "5999": "Разное",
    "6011": "Снятие наличных",
    "5310": "Магазины электроники",
    "7011": "Отели",
    "4411": "Такси / каршеринг",
    "5047": "Медицина",
    "4900": "ЖКХ",
    "8299": "Образование",
}

# ---------------------------------------------------------------------------
# Пул рекомендаций (сервер выбирает на основе скоринга и истории)
# ---------------------------------------------------------------------------
RECOMMENDATIONS = {
    "save_leftovers": {
        "id": "save_leftovers",
        "text": "Перевести остаток на накопительный — +8% годовых",
        "detail": "У тебя обычно остаётся ~12 000 ₽ к концу месяца",
        "cta": "Перевести",
        "action": "transfer_to_savings",
        "segment": ["young_professional"],
        "min_score": 600,
    },
    "optimize_subscriptions": {
        "id": "optimize_subscriptions",
        "text": "3 подписки на сумму 1 490 ₽/мес — есть дубли",
        "detail": "Яндекс.Плюс и отдельный Кинопоиск пересекаются",
        "cta": "Посмотреть",
        "action": "review_subscriptions",
        "segment": ["young_professional", "student"],
        "min_score": 0,
    },
    "cashback_boost": {
        "id": "cashback_boost",
        "text": "Подключи кэшбэк на супермаркеты — ты тратишь там 8 000 ₽/мес",
        "detail": "Категория «Продукты» у тебя топ-1 по расходам",
        "cta": "Подключить",
        "action": "enable_cashback_groceries",
        "segment": ["young_professional", "family"],
        "min_score": 500,
    },
    "deposit_offer": {
        "id": "deposit_offer",
        "text": "Открой вклад на 3 месяца — ставка 18% годовых",
        "detail": "Подходит для суммы от 50 000 ₽",
        "cta": "Открыть",
        "action": "open_deposit",
        "segment": ["investor", "family"],
        "min_score": 700,
    },
    "ttk_overdue_reminder": {
        "id": "ttk_overdue_reminder",
        "text": "⚠️ ТТК Интернет — платёж просрочен на 3 дня",
        "detail": "690 ₽ · счёт выставлен 8 апреля · оплати сейчас",
        "cta": "Оплатить",
        "action": "pay_ttk",
        "segment": ["family"],
        "min_score": 0,
    },
}

# ---------------------------------------------------------------------------
# Пул баннеров (персонализированные продуктовые предложения)
# ---------------------------------------------------------------------------
BANNERS = {
    "deposit_18": {
        "id": "deposit_18",
        "title": "Вклад «Выгодный»",
        "subtitle": "До 18% годовых · от 10 000 ₽ · 3 месяца",
        "action": "open_deposit",
        "segment": ["young_professional", "family", "investor"],
        "min_score": 600,
    },
    "student_credit": {
        "id": "student_credit",
        "title": "Кредит на образование",
        "subtitle": "До 500 000 ₽ · ставка 3% · отсрочка платежа",
        "action": "apply_student_credit",
        "segment": ["student"],
        "min_score": 0,
    },
    "mortgage_refinance": {
        "id": "mortgage_refinance",
        "title": "Рефинансирование ипотеки",
        "subtitle": "Ставка от 9.5% · снизь платёж",
        "action": "refinance_mortgage",
        "segment": ["family"],
        "min_score": 700,
    },
    "premium_card": {
        "id": "premium_card",
        "title": "Карта ВТБ Мир Supreme",
        "subtitle": "Кэшбэк 5% на всё · бесплатное обслуживание",
        "action": "apply_premium_card",
        "segment": ["investor", "family"],
        "min_score": 750,
    },
}

# ---------------------------------------------------------------------------
# ПОЛЬЗОВАТЕЛЬ: Витя — Студент, 22 года (Сегмент A — Must-Have, PIN 1111)
# Профиль из исследования: метро, «скинь за пиццу», текстовый ввод,
# страх неправильного распознавания голоса.
# ---------------------------------------------------------------------------
_VITYA = {
    "profile": {
        "user_id": "vitya",
        "full_name": "Исаев Виктор Игоревич",
        "display_name": "Витя И.",
        "birth_date": "2003-08-22",
        "age": 22,
        "phone": "+79161234001",
        "email": "vitya.isaev@student.spbgu.ru",
        "city": "Санкт-Петербург",
        "segment": "student",
        "score": 610,
        "rfm": {
            "recency_days": 1,
            "frequency_30d": 22,
            "monetary_30d": 14_800,
        },
        "is_salary_client": False,
        "salary_day": None,
        "months_as_client": 8,
        "active_products": ["debit", "savings"],
    },
    "accounts": [
        {
            "account_id": "debit",
            "account_type": "CurrentAccount",
            "name": "Дебетовая карта",
            "pan_masked": "4276 **** **** 1001",
            "balance": 8_540.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2025-08-01",
            "cashback_category": "Фастфуд",
            "cashback_rate": 0.05,
        },
        {
            "account_id": "savings",
            "account_type": "SavingsAccount",
            "name": "Накопительный счёт",
            "pan_masked": None,
            "balance": 2_100.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2026-02-01",
            "interest_rate": 0.08,
            "interest_accrued": 14.00,
        },
    ],
    "contacts": {
        "коля": {
            "display_name": "Николай Б.",
            "full_name": "Борисов Николай Андреевич",
            "phone": "+79161100011",
            "bank": "Сбер",
            "available_banks": ["Сбер", "Т-Банк"],
            "pan_masked": "4276 **** **** 2211",
            "transfer_count": 18,
            "last_transfer_date": "2026-04-09",
        },
        "коле": {  # дательный падеж
            "display_name": "Николай Б.",
            "full_name": "Борисов Николай Андреевич",
            "phone": "+79161100011",
            "bank": "Сбер",
            "available_banks": ["Сбер", "Т-Банк"],
            "pan_masked": "4276 **** **** 2211",
            "transfer_count": 18,
            "last_transfer_date": "2026-04-09",
        },
        "катя": {
            "display_name": "Екатерина С.",
            "full_name": "Смирнова Екатерина Владимировна",
            "phone": "+79265500022",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Альфа"],
            "pan_masked": "5536 **** **** 4422",
            "transfer_count": 7,
            "last_transfer_date": "2026-04-05",
        },
        "кате": {
            "display_name": "Екатерина С.",
            "full_name": "Смирнова Екатерина Владимировна",
            "phone": "+79265500022",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Альфа"],
            "pan_masked": "5536 **** **** 4422",
            "transfer_count": 7,
            "last_transfer_date": "2026-04-05",
        },
        "женя": {
            "display_name": "Евгений Р.",
            "full_name": "Романов Евгений Сергеевич",
            "phone": "+79031100033",
            "bank": "ВТБ",
            "available_banks": ["ВТБ"],
            "pan_masked": "4276 **** **** 3301",
            "transfer_count": 5,
            "last_transfer_date": "2026-03-28",
        },
        "мама": {
            "display_name": "Наталья И.",
            "full_name": "Исаева Наталья Петровна",
            "phone": "+79055600044",
            "bank": "Сбер",
            "available_banks": ["Сбер"],
            "pan_masked": "4276 **** **** 0044",
            "transfer_count": 2,
            "last_transfer_date": "2026-03-01",
        },
        "папа": {
            "display_name": "Игорь И.",
            "full_name": "Исаев Игорь Николаевич",
            "phone": "+79256700055",
            "bank": "ВТБ",
            "available_banks": ["ВТБ", "Сбер"],
            "pan_masked": "4276 **** **** 0055",
            "transfer_count": 1,
            "last_transfer_date": "2026-02-10",
        },
        "дима": {
            "display_name": "Дмитрий К.",
            "full_name": "Кузнецов Дмитрий Александрович",
            "phone": "+79967800066",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк"],
            "pan_masked": "5536 **** **** 6601",
            "transfer_count": 9,
            "last_transfer_date": "2026-04-08",
        },
        "диме": {
            "display_name": "Дмитрий К.",
            "full_name": "Кузнецов Дмитрий Александрович",
            "phone": "+79967800066",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк"],
            "pan_masked": "5536 **** **** 6601",
            "transfer_count": 9,
            "last_transfer_date": "2026-04-08",
        },
    },
    "scheduled_payments": [
        {
            "id": "SUB_V01",
            "name": "Яндекс.Плюс",
            "amount": 199.00,
            "day_of_month": 3,
            "category": "Подписки",
            "mcc": "5815",
            "status": "Active",
        },
        {
            "id": "SUB_V02",
            "name": "VK Combo",
            "amount": 149.00,
            "day_of_month": 7,
            "category": "Подписки",
            "mcc": "5815",
            "status": "Active",
        },
    ],
    "transactions": [
        # --- АПРЕЛЬ 2026 ---
        {
            "id": "TV2026041001",
            "booking_date": "2026-04-10",
            "value_date": "2026-04-10",
            "type": "Transfer",
            "amount": 250.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Дмитрий К.", "bank": "Т-Банк"},
            "category": "Переводы",
            "description": "За пиццу",
            "account_id": "debit",
        },
        {
            "id": "TV2026040901",
            "booking_date": "2026-04-09",
            "value_date": "2026-04-09",
            "type": "Purchase",
            "amount": 620.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Яндекс.Еда", "mcc": "5812", "city": "Санкт-Петербург"},
            "category": "Доставка еды",
            "description": "Ужин с колей",
            "account_id": "debit",
        },
        {
            "id": "TV2026040801",
            "booking_date": "2026-04-08",
            "value_date": "2026-04-08",
            "type": "Transfer",
            "amount": 400.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Николай Б.", "bank": "Сбер"},
            "category": "Переводы",
            "description": "За продукты",
            "account_id": "debit",
        },
        {
            "id": "TV2026040501",
            "booking_date": "2026-04-05",
            "value_date": "2026-04-05",
            "type": "Purchase",
            "amount": 180.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Метро (жетоны)", "mcc": "4111", "city": "Санкт-Петербург"},
            "category": "Транспорт",
            "description": "Проездной",
            "account_id": "debit",
        },
        {
            "id": "TV2026040301",
            "booking_date": "2026-04-03",
            "value_date": "2026-04-03",
            "type": "Purchase",
            "amount": 199.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Яндекс.Плюс", "mcc": "5815", "city": None},
            "category": "Подписки",
            "description": "Ежемесячная подписка",
            "account_id": "debit",
        },
        {
            "id": "TV2026040201",
            "booking_date": "2026-04-02",
            "value_date": "2026-04-02",
            "type": "TopUp",
            "amount": 200.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"phone": "+79161234001", "operator": "МТС"},
            "category": "Связь",
            "description": "Пополнение телефона",
            "account_id": "debit",
        },
        {
            "id": "TV2026040101",
            "booking_date": "2026-04-01",
            "value_date": "2026-04-01",
            "type": "Transfer",
            "amount": 500.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"display_name": "Наталья И.", "description": "На продукты"},
            "category": "Переводы входящие",
            "description": "От мамы",
            "account_id": "debit",
        },
        # --- МАРТ 2026 ---
        {
            "id": "TV2026033001",
            "booking_date": "2026-03-30",
            "value_date": "2026-03-30",
            "type": "Purchase",
            "amount": 550.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Burger King", "mcc": "5814", "city": "Санкт-Петербург"},
            "category": "Фастфуд",
            "description": "Обед",
            "account_id": "debit",
        },
        {
            "id": "TV2026032801",
            "booking_date": "2026-03-28",
            "value_date": "2026-03-28",
            "type": "Transfer",
            "amount": 350.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Евгений Р.", "bank": "ВТБ"},
            "category": "Переводы",
            "description": "Долг",
            "account_id": "debit",
        },
        {
            "id": "TV2026031001",
            "booking_date": "2026-03-10",
            "value_date": "2026-03-10",
            "type": "Credit",
            "amount": 5_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "СПбГУ", "description": "Стипендия за март"},
            "category": "Стипендия",
            "description": "Стипендия март 2026",
            "account_id": "debit",
        },
        {
            "id": "TV2026030701",
            "booking_date": "2026-03-07",
            "value_date": "2026-03-07",
            "type": "Credit",
            "amount": 25_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "ИП Борисов А.Н.", "description": "Подработка март"},
            "category": "Доходы",
            "description": "Подработка",
            "account_id": "debit",
        },
    ],
}

# ---------------------------------------------------------------------------
# ПОЛЬЗОВАТЕЛЬ: Ольга — Финансовый менеджер, 38 лет (Сегмент B, PIN 2222)
# Профиль из исследования: забытые платежи (ТТК), умные напоминания,
# Face ID, страх «кто-то увидит баланс».
# ---------------------------------------------------------------------------
_OLGA = {
    "profile": {
        "user_id": "olga",
        "full_name": "Орлова Ольга Михайловна",
        "display_name": "Ольга О.",
        "birth_date": "1987-03-15",
        "age": 38,
        "phone": "+79261234002",
        "email": "o.orlova@fingroup.ru",
        "city": "Санкт-Петербург",
        "segment": "family",
        "score": 760,
        "rfm": {
            "recency_days": 1,
            "frequency_30d": 31,
            "monetary_30d": 68_400,
        },
        "is_salary_client": True,
        "salary_day": 10,
        "months_as_client": 42,
        "active_products": ["debit", "savings"],
    },
    "accounts": [
        {
            "account_id": "debit",
            "account_type": "CurrentAccount",
            "name": "Дебетовая карта",
            "pan_masked": "4276 **** **** 2002",
            "balance": 87_340.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2022-09-01",
            "cashback_category": "Супермаркеты",
            "cashback_rate": 0.03,
        },
        {
            "account_id": "savings",
            "account_type": "SavingsAccount",
            "name": "Накопительный счёт",
            "pan_masked": None,
            "balance": 485_000.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2022-11-01",
            "interest_rate": 0.09,
            "interest_accrued": 29_700.00,
        },
    ],
    "contacts": {
        "сережа": {
            "display_name": "Сергей О.",
            "full_name": "Орлов Сергей Владимирович",
            "phone": "+79161300020",
            "bank": "ВТБ",
            "available_banks": ["ВТБ", "Сбер"],
            "pan_masked": "4276 **** **** 2020",
            "transfer_count": 24,
            "last_transfer_date": "2026-04-08",
        },
        "сергей": {
            "display_name": "Сергей О.",
            "full_name": "Орлов Сергей Владимирович",
            "phone": "+79161300020",
            "bank": "ВТБ",
            "available_banks": ["ВТБ", "Сбер"],
            "pan_masked": "4276 **** **** 2020",
            "transfer_count": 24,
            "last_transfer_date": "2026-04-08",
        },
        "мурат": {
            "display_name": "Мурат Д.",
            "full_name": "Дюсенов Мурат Алибекович",
            "phone": "+79273400021",
            "bank": "Альфа",
            "available_banks": ["Альфа", "Т-Банк"],
            "pan_masked": "4279 **** **** 2121",
            "transfer_count": 6,
            "last_transfer_date": "2026-03-25",
        },
        "ирина": {
            "display_name": "Ирина В.",
            "full_name": "Власова Ирина Сергеевна",
            "phone": "+79115400022",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк"],
            "pan_masked": "5536 **** **** 2222",
            "transfer_count": 4,
            "last_transfer_date": "2026-04-01",
        },
        "ира": {
            "display_name": "Ирина В.",
            "full_name": "Власова Ирина Сергеевна",
            "phone": "+79115400022",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк"],
            "pan_masked": "5536 **** **** 2222",
            "transfer_count": 4,
            "last_transfer_date": "2026-04-01",
        },
        "мама": {
            "display_name": "Галина П.",
            "full_name": "Петрова Галина Ивановна",
            "phone": "+79055600023",
            "bank": "Сбер",
            "available_banks": ["Сбер"],
            "pan_masked": "4276 **** **** 0023",
            "transfer_count": 12,
            "last_transfer_date": "2026-03-28",
        },
        "аня": {
            "display_name": "Анна О.",
            "full_name": "Орлова Анна Сергеевна",
            "phone": "+79256700024",
            "bank": "ВТБ",
            "available_banks": ["ВТБ"],
            "pan_masked": "4276 **** **** 0024",
            "transfer_count": 16,
            "last_transfer_date": "2026-04-07",
        },
        "дмитрий": {
            "display_name": "Дмитрий Р.",
            "full_name": "Романов Дмитрий Петрович",
            "phone": "+79851300025",
            "bank": "ВТБ",
            "available_banks": ["ВТБ", "Сбер"],
            "pan_masked": "4276 **** **** 0025",
            "transfer_count": 3,
            "last_transfer_date": "2026-03-15",
        },
    },
    "scheduled_payments": [
        {
            "id": "SUB_O01",
            "name": "ТТК Интернет",
            "amount": 690.00,
            "day_of_month": 8,
            "category": "Интернет",
            "mcc": "4900",
            "status": "Overdue",   # ← ЗАБЫТЫЙ ПЛАТЁЖ — боль персоны!
        },
        {
            "id": "SUB_O02",
            "name": "Ипотека ВТБ",
            "amount": 38_500.00,
            "day_of_month": 5,
            "category": "Ипотека",
            "mcc": "4900",
            "status": "Active",
        },
        {
            "id": "SUB_O03",
            "name": "ЖКХ — УК Центральная",
            "amount": 6_800.00,
            "day_of_month": 25,
            "category": "ЖКХ",
            "mcc": "4900",
            "status": "Active",
        },
        {
            "id": "SUB_O04",
            "name": "Яндекс.Плюс Family",
            "amount": 399.00,
            "day_of_month": 12,
            "category": "Подписки",
            "mcc": "5815",
            "status": "Active",
        },
    ],
    "transactions": [
        # --- АПРЕЛЬ 2026 ---
        {
            "id": "TO2026041001",
            "booking_date": "2026-04-10",
            "value_date": "2026-04-10",
            "type": "Credit",
            "amount": 125_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "ООО ФинГрупп", "description": "Зарплата за март"},
            "category": "Зарплата",
            "description": "Зарплата март 2026",
            "account_id": "debit",
        },
        {
            "id": "TO2026040801",
            "booking_date": "2026-04-08",
            "value_date": "2026-04-08",
            "type": "Transfer",
            "amount": 5_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Сергей О.", "bank": "ВТБ"},
            "category": "Переводы",
            "description": "На продукты",
            "account_id": "debit",
        },
        {
            "id": "TO2026040701",
            "booking_date": "2026-04-07",
            "value_date": "2026-04-07",
            "type": "Transfer",
            "amount": 3_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Анна О.", "bank": "ВТБ"},
            "category": "Переводы",
            "description": "Карманные",
            "account_id": "debit",
        },
        {
            "id": "TO2026040601",
            "booking_date": "2026-04-06",
            "value_date": "2026-04-06",
            "type": "Purchase",
            "amount": 5_240.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Перекрёсток", "mcc": "5411", "city": "Санкт-Петербург"},
            "category": "Супермаркеты",
            "description": "Продукты на неделю",
            "account_id": "debit",
        },
        {
            "id": "TO2026040501",
            "booking_date": "2026-04-05",
            "value_date": "2026-04-05",
            "type": "Purchase",
            "amount": 38_500.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "ВТБ Ипотека", "mcc": "4900", "city": None},
            "category": "Ипотека",
            "description": "Ежемесячный платёж по ипотеке",
            "account_id": "debit",
        },
        {
            "id": "TO2026040101",
            "booking_date": "2026-04-01",
            "value_date": "2026-04-01",
            "type": "Transfer",
            "amount": 1_200.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Ирина В.", "bank": "Т-Банк"},
            "category": "Переводы",
            "description": "Обед с коллегами",
            "account_id": "debit",
        },
        # --- МАРТ 2026 ---
        {
            "id": "TO2026033001",
            "booking_date": "2026-03-30",
            "value_date": "2026-03-30",
            "type": "Purchase",
            "amount": 1_890.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Аптека 36.6", "mcc": "5912", "city": "Санкт-Петербург"},
            "category": "Аптеки",
            "description": "Лекарства для семьи",
            "account_id": "debit",
        },
        {
            "id": "TO2026032801",
            "booking_date": "2026-03-28",
            "value_date": "2026-03-28",
            "type": "Transfer",
            "amount": 2_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Галина П.", "bank": "Сбер"},
            "category": "Переводы",
            "description": "Маме",
            "account_id": "debit",
        },
        {
            "id": "TO2026032501",
            "booking_date": "2026-03-25",
            "value_date": "2026-03-25",
            "type": "Purchase",
            "amount": 6_800.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "УК Центральная", "mcc": "4900", "city": "Санкт-Петербург"},
            "category": "ЖКХ",
            "description": "Коммунальные март",
            "account_id": "debit",
        },
        {
            "id": "TO2026031001",
            "booking_date": "2026-03-10",
            "value_date": "2026-03-10",
            "type": "Credit",
            "amount": 125_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "ООО ФинГрупп", "description": "Зарплата за февраль"},
            "category": "Зарплата",
            "description": "Зарплата февраль 2026",
            "account_id": "debit",
        },
    ],
}

# ---------------------------------------------------------------------------
# ПОЛЬЗОВАТЕЛЬ: Артём — Маркетолог, 29 лет (Сегмент A/B, PIN 3333)
# Профиль из исследования: репетитор по вторникам, виджет как пассивный
# дашборд, страх «ещё один инструмент».
# ---------------------------------------------------------------------------
_ARTYOM = {
    "profile": {
        "user_id": "artyom",
        "full_name": "Захаров Артём Павлович",
        "display_name": "Артём З.",
        "birth_date": "1996-11-05",
        "age": 29,
        "phone": "+79031234003",
        "email": "artyom.zakharov@agency.ru",
        "city": "Санкт-Петербург",
        "segment": "young_professional",
        "score": 695,
        "rfm": {
            "recency_days": 1,
            "frequency_30d": 35,
            "monetary_30d": 58_200,
        },
        "is_salary_client": True,
        "salary_day": 10,
        "months_as_client": 26,
        "active_products": ["debit", "credit", "savings"],
    },
    "accounts": [
        {
            "account_id": "debit",
            "account_type": "CurrentAccount",
            "name": "Дебетовая карта",
            "pan_masked": "4276 **** **** 3003",
            "balance": 35_820.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2024-01-20",
            "cashback_category": "Рестораны",
            "cashback_rate": 0.05,
        },
        {
            "account_id": "credit",
            "account_type": "CreditCard",
            "name": "Кредитная карта ВТБ",
            "pan_masked": "4272 **** **** 3033",
            "balance": -18_500.00,
            "credit_limit": 80_000.00,
            "available_credit": 61_500.00,
            "min_payment": 1_850.00,
            "payment_due_date": "2026-04-20",
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2024-06-15",
            "cashback_rate": 0.01,
        },
        {
            "account_id": "savings",
            "account_type": "SavingsAccount",
            "name": "Накопительный счёт",
            "pan_masked": None,
            "balance": 75_000.00,
            "currency": "RUB",
            "status": "Enabled",
            "open_date": "2024-04-01",
            "interest_rate": 0.08,
            "interest_accrued": 4_200.00,
        },
    ],
    "contacts": {
        "настя": {
            "display_name": "Анастасия Л.",
            "full_name": "Лебедева Анастасия Дмитриевна",
            "phone": "+79261300030",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Сбер"],
            "pan_masked": "5536 **** **** 3030",
            "transfer_count": 28,
            "last_transfer_date": "2026-04-09",
        },
        "насте": {
            "display_name": "Анастасия Л.",
            "full_name": "Лебедева Анастасия Дмитриевна",
            "phone": "+79261300030",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Сбер"],
            "pan_masked": "5536 **** **** 3030",
            "transfer_count": 28,
            "last_transfer_date": "2026-04-09",
        },
        "максим": {
            "display_name": "Максим Г.",
            "full_name": "Горбунов Максим Игоревич",
            "phone": "+79031300031",
            "bank": "ВТБ",
            "available_banks": ["ВТБ"],
            "pan_masked": "4276 **** **** 3031",
            "transfer_count": 11,
            "last_transfer_date": "2026-04-05",
        },
        "макс": {
            "display_name": "Максим Г.",
            "full_name": "Горбунов Максим Игоревич",
            "phone": "+79031300031",
            "bank": "ВТБ",
            "available_banks": ["ВТБ"],
            "pan_masked": "4276 **** **** 3031",
            "transfer_count": 11,
            "last_transfer_date": "2026-04-05",
        },
        "тамара": {
            "display_name": "Тамара Ф.",
            "full_name": "Фёдорова Тамара Николаевна",
            "phone": "+79851300032",
            "bank": "Сбер",
            "available_banks": ["Сбер"],
            "pan_masked": "4276 **** **** 3032",
            "transfer_count": 14,
            "last_transfer_date": "2026-04-08",
        },
        "паша": {
            "display_name": "Павел Н.",
            "full_name": "Никитин Павел Андреевич",
            "phone": "+79161300033",
            "bank": "Альфа",
            "available_banks": ["Альфа", "Т-Банк"],
            "pan_masked": "4279 **** **** 3033",
            "transfer_count": 7,
            "last_transfer_date": "2026-03-28",
        },
        "мама": {
            "display_name": "Ольга З.",
            "full_name": "Захарова Ольга Борисовна",
            "phone": "+79055600034",
            "bank": "Сбер",
            "available_banks": ["Сбер"],
            "pan_masked": "4276 **** **** 0034",
            "transfer_count": 5,
            "last_transfer_date": "2026-03-08",
        },
        "иван": {
            "display_name": "Иван М.",
            "full_name": "Морозов Иван Сергеевич",
            "phone": "+79967800035",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Сбер"],
            "pan_masked": "5536 **** **** 3035",
            "transfer_count": 8,
            "last_transfer_date": "2026-04-06",
        },
        "ваня": {
            "display_name": "Иван М.",
            "full_name": "Морозов Иван Сергеевич",
            "phone": "+79967800035",
            "bank": "Т-Банк",
            "available_banks": ["Т-Банк", "Сбер"],
            "pan_masked": "5536 **** **** 3035",
            "transfer_count": 8,
            "last_transfer_date": "2026-04-06",
        },
    },
    "scheduled_payments": [
        {
            "id": "SUB_A01",
            "name": "FitBox Premium",
            "amount": 3_500.00,
            "day_of_month": 1,
            "category": "Спорт",
            "mcc": "7941",
            "status": "Active",
        },
        {
            "id": "SUB_A02",
            "name": "Netflix",
            "amount": 799.00,
            "day_of_month": 14,
            "category": "Подписки",
            "mcc": "5815",
            "status": "Active",
        },
        {
            "id": "SUB_A03",
            "name": "Яндекс.Плюс",
            "amount": 399.00,
            "day_of_month": 3,
            "category": "Подписки",
            "mcc": "5815",
            "status": "Active",
        },
        {
            "id": "SUB_A04",
            "name": "Репетитор Тамара",
            "amount": 2_000.00,
            "day_of_month": None,  # каждый вторник — нерегулярно
            "weekday": "tuesday",
            "category": "Образование",
            "mcc": "8299",
            "status": "Active",
        },
    ],
    "transactions": [
        # --- АПРЕЛЬ 2026 ---
        {
            "id": "TA2026041001",
            "booking_date": "2026-04-10",
            "value_date": "2026-04-10",
            "type": "Credit",
            "amount": 85_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "ООО Агентство Маркетинг", "description": "Зарплата за март"},
            "category": "Зарплата",
            "description": "Зарплата март 2026",
            "account_id": "debit",
        },
        {
            "id": "TA2026040901",
            "booking_date": "2026-04-09",
            "value_date": "2026-04-09",
            "type": "Transfer",
            "amount": 3_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Анастасия Л.", "bank": "Т-Банк"},
            "category": "Переводы",
            "description": "Концерт",
            "account_id": "debit",
        },
        {
            "id": "TA2026040801",
            "booking_date": "2026-04-08",
            "value_date": "2026-04-08",
            "type": "Transfer",
            "amount": 2_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Тамара Ф.", "bank": "Сбер"},
            "category": "Образование",
            "description": "Репетитор (вторник)",
            "account_id": "debit",
        },
        {
            "id": "TA2026040601",
            "booking_date": "2026-04-06",
            "value_date": "2026-04-06",
            "type": "Purchase",
            "amount": 1_850.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Кофемания", "mcc": "5812", "city": "Санкт-Петербург"},
            "category": "Кафе и рестораны",
            "description": "Встреча с клиентом",
            "account_id": "debit",
        },
        {
            "id": "TA2026040501",
            "booking_date": "2026-04-05",
            "value_date": "2026-04-05",
            "type": "Transfer",
            "amount": 1_500.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Максим Г.", "bank": "ВТБ"},
            "category": "Переводы",
            "description": "За выходные",
            "account_id": "debit",
        },
        {
            "id": "TA2026040301",
            "booking_date": "2026-04-03",
            "value_date": "2026-04-03",
            "type": "Purchase",
            "amount": 399.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "Яндекс.Плюс", "mcc": "5815", "city": None},
            "category": "Подписки",
            "description": "Ежемесячная подписка",
            "account_id": "debit",
        },
        {
            "id": "TA2026040101",
            "booking_date": "2026-04-01",
            "value_date": "2026-04-01",
            "type": "Purchase",
            "amount": 3_500.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "FitBox Premium", "mcc": "7941", "city": "Санкт-Петербург"},
            "category": "Спорт",
            "description": "Абонемент апрель",
            "account_id": "debit",
        },
        # --- МАРТ 2026 ---
        {
            "id": "TA2026033101",
            "booking_date": "2026-03-31",
            "value_date": "2026-03-31",
            "type": "Purchase",
            "amount": 4_200.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": {"name": "OZON", "mcc": "5999", "city": None},
            "category": "Онлайн-покупки",
            "description": "Товары для дома",
            "account_id": "credit",
        },
        {
            "id": "TA2026032501",
            "booking_date": "2026-03-25",
            "value_date": "2026-03-25",
            "type": "Transfer",
            "amount": 2_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Тамара Ф.", "bank": "Сбер"},
            "category": "Образование",
            "description": "Репетитор (вторник)",
            "account_id": "debit",
        },
        {
            "id": "TA2026031001",
            "booking_date": "2026-03-10",
            "value_date": "2026-03-10",
            "type": "Credit",
            "amount": 85_000.00,
            "currency": "RUB",
            "direction": "credit",
            "status": "Posted",
            "merchant": None,
            "sender": {"name": "ООО Агентство Маркетинг", "description": "Зарплата за февраль"},
            "category": "Зарплата",
            "description": "Зарплата февраль 2026",
            "account_id": "debit",
        },
        {
            "id": "TA2026030801",
            "booking_date": "2026-03-08",
            "value_date": "2026-03-08",
            "type": "Transfer",
            "amount": 3_000.00,
            "currency": "RUB",
            "direction": "debit",
            "status": "Posted",
            "merchant": None,
            "recipient": {"display_name": "Анастасия Л.", "bank": "Т-Банк"},
            "category": "Переводы",
            "description": "8 марта",
            "account_id": "debit",
        },
    ],
}

# ---------------------------------------------------------------------------
# USERS — единый реестр пользователей
# ---------------------------------------------------------------------------
USERS: dict[str, dict] = {
    "vitya":  _VITYA,
    "olga":   _OLGA,
    "artyom": _ARTYOM,
}

# ---------------------------------------------------------------------------
# Phone index (нормализованный номер → (user_id, contact_key))
# Строится один раз при старте из всех контактов всех пользователей
# ---------------------------------------------------------------------------
PHONE_INDEX: dict[str, tuple[str, str]] = {}


def _normalize_phone(phone: str) -> str:
    digits = "".join(c for c in phone if c.isdigit())
    if len(digits) == 11 and digits[0] in ("7", "8"):
        return "7" + digits[1:]
    if len(digits) == 10:
        return "7" + digits
    return digits


def build_phone_index() -> None:
    seen_phones: set[str] = set()
    for user_id, user_data in USERS.items():
        for key, contact in user_data["contacts"].items():
            norm = _normalize_phone(contact["phone"])
            if norm and norm not in seen_phones:
                PHONE_INDEX[norm] = (user_id, key)
                seen_phones.add(norm)


build_phone_index()
